from .template_node_processor import TemplateNodeProcessor
from .prompt_node_processor import PromptNodeProcessor
from .run_node_processor import RunNodeProcessor
from .registry import NodeProcessorRegistry 